add chat
OpenLWR/OpenLWR-Server pull request #16
Opened 2024-06-09 16:43 UTC by kcinnaJlol

2024-06-09 21:00 UTC, watchful5406 requested changes
chat should close when the user clicks anywhere else but it

2024-06-09 21:02 UTC, watchful5406 requested changes
new chat messages should disappear after some time to avoid clogging up the screen (or make it possible to close)

2024-06-09 22:53 UTC, SakuruWasTaken commented
> chat should close when the user clicks anywhere else but it



> new chat messages should disappear after some time to avoid clogging up the screen (or make it possible to close)


these should be moved over to https://github.com/OpenLWR/OpenLWR/pull/11

2024-06-09 22:59 UTC, SakuruWasTaken commented on server/client_events/client_chat_event.py
> +    server_chat_event.fire("{1}: {0}".format(data, source_user))
i don't think it's a great idea to just send the message over without doing any kind of validation at all, if i wanted to annoy users by sending a message 30000 chars long, there'd be nothing to stop me from doing that here.

(i'll add this on my own after merge, you don't need to do anything here)

2024-06-09 23:06 UTC, SakuruWasTaken approved these changes

2024-06-28 02:51 UTC, watchful5406 approved these changes

2024-06-28 02:52 UTC, merged